### ISSUE TITLE
Maps won't display inline on latest Jupyter/IPython

### ISSUE THREAD

**Issue by MatthewTurk** [jwass/mplleaflet#12]
Hi, I'm running master of IPython/Jupyter (e013d522d028f98e73f08f057b27cf06d055d43a) and I'm not able to get the widgets to display properly.  Running the simple example of:

```python
%matplotlib inline
import mplleaflet
mplleaflet.display(tiles="mapbox bright")
```

the box displays, it has the zoom buttons and the leaflet attribution, but it's blank.  In the javascript console, the error is `Uncaught TypeError: Cannot read property 'lat' of undefined`.  I'm wondering if this could be related to changes in how javascript has to be loaded in the current version of IPython?  Any suggestions?

**Comment by jwass** [comment]
Hi @MatthewTurk.

There was an issue with calling mplleaflet with an empty plot that caused the behavior you're seeing. Can you try to add some data with something like:
```
%matplotlib inline
import mplleaflet
import matplotlib.pyplot as plt
plt.plot([0,45], [0,45])
mplleaflet.display()
```

and see if that works?

I also fixed the empty plot bug in 8a3ec45bd698d76a9df6812e7738dce65a0a2465. Can you also try your original posted code and close the issue if it works for you? Otherwise let us know.

**Comment by MatthewTurk** [comment]
Thanks, @jwass, all is well now!

**Comment by jwass** [comment]
@MatthewTurk Great to know! Thanks for verifying.
